server:
  port: 8081

spring:
  application:
    name: ads-service
  datasource:
    url: jdbc:postgresql://postgres:5433/jiraffle
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver