services:
  api-gateway:
    image: jiraffle-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  ads-service:
    image: mjiraffle-ads:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  analytics-service:
    image: jiraffle-analytics:latest
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  auth-service:
    image: jiraffle-auth:latest
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  task-service:
    image: jiraffle-task:latest
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  repo-service:
    image: jiraffle-repo:latest
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  docs-service:
    image: jiraffle-docs:latest
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  notification-service:
    image: jiraffle-notification:latest
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  automation-service:
    image: jiraffle-automation:latest
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  frontend:
    image: jiraffle-frontend:latest
    ports:
      - "80:80"
    restart: unless-stopped